### ISSUE TITLE
Undefined reference when run project after update dependencies

### ISSUE THREAD

**Issue by hsb12001** [michaeltroger/feature-matching-native-android#2]
Hello, any person who can help me with the following error that appears to me after updating some dependencies of the same project since I have downloaded it in Android Studio 3.4, targetSdkVersion 29, compileSdkVersion 29, AndroidX, replacement of gnustl_static by c++_static. The error is as follows

feature-matching-native/app/src/main/cpp/native_opencv.cpp:86: error: undefined reference to 'cv::DescriptorMatcher::match(cv::_InputArray const&, cv::_InputArray const&, std::__ndk1::vector<cv::DMatch, std::__ndk1::allocator<cv::DMatch> >&, cv::_InputArray const&) const'

Any ideas.

**Comment by xiongzhu666** [comment]
I face the same problem now....how did you solve it finally???thanks

**Comment by hsb12001** [comment]
Sorry I couldn't get it to work after 1 week of working with the libraries
update.

 Best regards

**Comment by andy6804tw** [comment]
@xiongzhu666 @hsb12001 
Hi, I fix this problem. You can clone it from here.
https://github.com/andy6804tw/feature-matching-native

**Comment by hsb12001** [comment]
Thanks by take you time for read my question and fix problem i review new
version.


Greetings friend.

**Comment by michaeltroger** [comment]
Apologies! Over the years I lost track about this repository.
@andy6804tw thx for helping out here.

@hsb12001 @xiongzhu666 
Meanwhile I updated the project to use updated SDK, NDK, OpenCV, AndroidX, Gradle, converted it to Kotlin and added a runtime camera permission check. I also checked it works with the latest Android Studio 2020.3.1

If you're interested in the root cause for your issue:
NDK versions > v16 are built with libc++ while OpenCV 3 is built with gnustl.
See also [Stackoverflow Post](https://stackoverflow.com/a/50686467/5155371) and [NDK Changelog](https://github.com/android/ndk/wiki/Changelog-r17)
It can be fixed by forcing NDK v16 or by compiling OpenCV yourself with libc++.
Both fix versions can be found in the updated repo. But the latest repo version uses the latest NDK approach.

I consider this ticket now as outdated and will close it. Ping me if you have any other issue.
